services:
  db:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=$drodos_postgres_user
      - POSTGRES_PASSWORD=$drodos_postgres_password
    volumes:
      - db_data:/var/lib/postgresql/data:Z  # create volume for DB persistence
  web:
    build: .
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=$drodos_postgres_user
      - POSTGRES_PASSWORD=$drodos_postgres_password
    entrypoint: /drodos/entrypoint_dev.sh
    volumes:
      - ./drodos:/drodos/drodos:Z     # bind drodos folder to host os
      - ./dropbox:/drodos/dropbox:Z   # bind app folder to host os
      - ./media:/data/media:Z #bind drodos file storage
    ports:
      - "8000:8000"
    depends_on:
      - db
volumes:
  db_data: